// Generated by https://quicktype.io

export interface Races {
  count:   number;
  results: Result[];
}

export interface Result {
  index: string;
  name:  string;
  url:   string;
}
// Generated by https://quicktype.io

export interface Race {
  index:                  string;
  name:                   string;
  speed:                  number;
  ability_bonuses:        AbilityBonus[];
  alignment:              string;
  age:                    string;
  size:                   string;
  size_description:       string;
  starting_proficiencies: any[];
  languages:              Language[];
  language_desc:          string;
  traits:                 Language[];
  subraces:               any[];
  url:                    string;
}

export interface AbilityBonus {
  ability_score: Language;
  bonus:         number;
}

export interface Language {
  index: string;
  name:  string;
  url:   string;
}
